// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package questionComponents

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "echo-test/components"

type FormBodyProps struct {
	QuestionTypes []components.SelectValues
	Errors        map[string]string
}

func FormBody(props FormBodyProps) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"new-question\" class=\"flex flex-col gap-3\"><div class=\"grid grid-cols-1 lg:grid-cols-3 gap-3 mt-6\"><div class=\"col-span-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInput(components.TextInputProps{Name: "question-name", Placeholder: "Question name", Label: "Question name", Model: "questionName", ID: "question-name-input", Required: true, Error: props.Errors["QuestionName"]}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"col-span-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.SelectInput(components.SelectInputProps{Name: "question-type", Label: "Question type", Model: "questionType", ID: "question-type-input", Values: props.QuestionTypes}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"col-span-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.NumberInput(components.NumberInputProps{Name: "question-points", Placeholder: "Points", Label: "Points for question", Model: "questionPoints", ID: "question-points-input", Required: true, Min: "0", Error: props.Errors["QuestionPoints"]}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"col-span-1 lg:col-span-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextArea(components.TextAreaProps{Name: "question-text", Placeholder: "Formulate your question.", Label: "Question text", Model: "questionText", ID: "question-text-input", Required: true, Error: props.Errors["QuestionText"]}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><div class=\"divider w-full\"></div><div class=\"prose flex align-baseline gap-3\"><h2>Answers Definition</h2><button @click=\"addAnswer\" class=\"btn btn-outline btn-sm btn-success\" type=\"button\">New</button></div><template id=\"answers-definition-list\" x-for=\"(answer, index) in answers\" :key=\"answer.id\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = AnswerDefinitionRow().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</template><div class=\"divider w-full\"></div><div class=\"ml-auto\"><button hx-post=\"/question\" hx-target=\"#new-question\" hx-swap=\"outerHTML\" hx-target class=\"btn btn-primary\">Create Question</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
