// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package questionComponents

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "echo-test/components"

type FormBodyProps struct {
	QuestionTypes []components.SelectValues
}

func FormBody(props FormBodyProps) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"new-question\" class=\"flex flex-col gap-3\"><div class=\"grid grid-cols-1 lg:grid-cols-3 gap-3 mt-6\"><div class=\"col-span-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInput(components.TextInputProps{Name: "question-name", Placeholder: "Question name", Label: "Question name", ID: "question-name-input", Required: true, InputAttrs: templ.Attributes{"data-create-question-target": "questionNameInput"}}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"col-span-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.SelectInput(components.SelectInputProps{Name: "question-type", Label: "Question type", ID: "question-type-input", Values: props.QuestionTypes, InputAttrs: templ.Attributes{"data-create-question-target": "questionTypeInput"}}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"col-span-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.NumberInput(components.NumberInputProps{Name: "question-points", Placeholder: "Points", Label: "Points for question", ID: "question-points-input", Required: true, Min: "0", InputAttrs: templ.Attributes{"data-create-question-target": "questionPointsInput"}}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"col-span-1 lg:col-span-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextArea(components.TextAreaProps{Name: "question-text", Placeholder: "Formulate your question.", Label: "Question text", ID: "question-text-input", Required: true, InputAttrs: templ.Attributes{"data-create-question-target": "questionTextInput"}}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><div class=\"divider w-full\"></div><div class=\"prose flex align-baseline gap-3\"><h2>Answers Definition</h2><input name=\"questions-count\" type=\"hidden\" data-create-question-target=\"questionsCountInput\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString("0"))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"> <button hx-get=\"/question/add-answer\" hx-target=\"#answer-list\" hx-include=\"[name=&#39;questions-count&#39;]\" hx-swap=\"beforeend\" class=\"btn btn-outline btn-sm btn-success\" type=\"button\">New</button></div><div id=\"answer-list\" data-create-question-target=\"answerList\"></div><div class=\"divider w-full\"></div><div class=\"ml-auto mb-3\"><button hx-post=\"/question\" hx-swap=\"none\" class=\"btn btn-primary\">Create Question</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
