// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package testComponents

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "echo-test/components"

type CreateTestStepScoreProps struct {
	Erors map[string]string
}

func CreateTestStepScore(props CreateTestStepScoreProps) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div x-init=\"currentStep = 2\" class=\"flex flex-col justify-between flex-1 h-full\"><div id=\"maximal-score\" class=\"grid grid-cols-2 lg:grid-cols-5 gap-5 w-full\"><div class=\"col-span-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.NumberInput(components.NumberInputProps{Label: "Maximum points", Name: "max-score", Min: "10", Required: true, Model: "maxScore", Error: props.Erors["MaxScore"]}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div id=\"min-required-score\" class=\"col-span-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.NumberInput(components.NumberInputProps{Label: "Minimal score required", Name: "min-required-score", Min: "10", Required: true, Model: "minRequiredScore", Error: props.Erors["MinRequiredScore"]}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><div class=\" mt-auto mb-4 flex justify-between\"><button hx-post=\"/test/new/step1\" hx-target=\"#create-test-form-step-1\" type=\"button\" class=\"btn btn-primary self-end\">Previous Step</button> <button hx-post=\"/test/new/step3\" hx-target=\"#create-test-form-step-3\" type=\"button\" class=\"btn btn-primary self-end\">Next Step</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
